os:
  - linux
language: dart
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - cd app_feup
  - ../flutter/bin/flutter doctor
  - ../flutter/bin/flutter packages get
  - cd ..
dart_task:
  - dartanalyzer: --fatal-warnings --options app_feup/analysis_options.yaml app_feup/lib 
cache:
  directories:
    - $HOME/.pub-cache